apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-web
  template:
    metadata:
      labels:
        app: conversao-web
    spec:
      containers:
      - name: conversao-web
        image: leandrojbraga/kubedev-desafio3-conversao:v1
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-web
spec:
  selector:
    app: conversao-web
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort
